version: '3.8'

services:
    app:
      container_name: weather_app
      image: weather-app-react
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - '.:/app'
        - '/app/node_modules'
      ports:
        - "3000:3000"
